### ISSUE TITLE
Implement BoardGameGeek ID extraction from board game title

### ISSUE THREAD

**Issue by havanagrawal** [havanagrawal/wikidata-toolkit#12]
## Problem

Implement the `board_game_geek_id` function in [`external_identifier`](./../blob/master/external_identifier.py)

## Prerequisites

- [ ] You know basic git, i.e. how to fork this repo, clone this repo, work on a branch and send a PR
- [ ] You have basic working knowledge of Python
- [ ] You are able to run Python on your machine
- [ ] You are familiar with basic web scraping (example: `requests`, `bs4` (BeautifulSoup), etc)

## How to Test

Simply run `python3 external_identifier.py` and it will run [doctests](https://docs.python.org/3/library/doctest.html). Ensure that the test for `board_game_geek_id` passes. 

## Hints

 * Try searching for some movie on https://boardgamegeek.com. What does the URL look like? You can use that to send a GET request.
 * Feel free to add more arguments to the function if they help in increasing the confidence of the returned identifier.

**Comment by saikirankv** [comment]
@havanagrawal  can I take this?
